blog/App/views.py
#!/usr/bin/env python
# encoding: utf-8
'''
@desc:    
@author:  
@contact: 
@file: views.py
@time: 2020/2/28 9:22 上午
'''
import hashlib
from random import randint

from flask import Blueprint, render_template, request, redirect, session, jsonify, make_response, url_for, flash
from flask_login import login_required, logout_user, login_user
from werkzeug.security import generate_password_hash,check_password_hash

from App import models
from App.SMS import sms
from App.forms import RegisterCheck, MarkCheck
from App.models import *
from App.verifycode import vc

bp = Blueprint('bp',__name__)
us = Blueprint("us",__name__,url_prefix='/user')

@bp.route("/")
def index():
    #查询文章数据
    articles = Article.query.all()
    three_articles = Article.query.order_by(-Article.create_time).all()[:3]
    three = len(three_articles)
    return render_template("index.html",**locals())

# 博文分类展示
@bp.route("/list/")
@bp.route("/list/<int:cid>/")
@bp.route("/list/<int:cid>/<int:page>")
def list_article(cid=1,page=1):
    if cid < 0: # 如果cid不带参数，值-1，就查询默认分类
        # 获取默认分类中所有的文章数据
        category = Category.query.first()
        cid = category.cid  # 获取第一个cid
    # if page <0:
    #     page = 2
    articles = db.session.query(Article, Category).filter(Article.cid == Category.cid, Category.cid == cid).all()
    pagination = db.session.query(Article, Category).filter(Article.cid == Category.cid, Category.cid == cid).paginate(page,2)
    article_num = len(articles)
    # 按照分类获得每个分类的数量
    categorys = Category.query.all()
    category_num = len(categorys)
    cidnum = db.session.execute("select cid,count(cid) from article group by cid").fetchall()
    cid_num = len(cidnum)
    # 提取分类数据
    categories = Category.query.all()
    # print(categories[cid].name)
    # 提取标签
    # time = datetime.utcnow()
    # print(time)
    tags = Tag.query.all()
    tags_num = len(tags)
    # 最近3篇文章
    three_articles = Article.query.order_by(-Article.create_time).all()[:3]
    three = len(three_articles)
    # print(three_articles)
    return render_template("blog.html",**locals())

# @bp.route("/page/<int:page>/")
# def list_user(page=2):
#     # 搞清楚页码和记录关系：limit (page-1)*10,10
#     # 获取分页对象 .group_by( User.sex).all()
#     # a = db.session.query(Article, Category).filter(Article.cid == Category.cid).all()
#     # print(a)
#     pagination = Article.query.paginate(page, 2)
#     # pagination = db.session.query(Article, Category).filter(Article.cid == Category.cid).paginate(page,1)
#     print(pagination.__dict__)
#     return render_template("list.html",**locals())


@bp.route("/post/")
@bp.route("/post/<int:aid>/")
def list_post(aid=0):
    # if aid > 0: # 如果cid不带参数，值-1，就查询默认分类
    #     # 获取默认分类中所有的文章数据
    #     article = Article.query.first()
    #     aid = article.aid # 获取第一个cid
    categories = Category.query.all()
    category = Category.query.first()
    # print(category)
    cid = category.cid  # 获取第一个cid
    articles = Article.query.all()
    article_num = len(articles)
    # 提取分类数据
    tags = Tag.query.all()
    tags_num = len(tags)
    # 根据ａｉｄ获取ｔａｇ的值
    tag = db.session.query(Tag).filter(Article.aid == Tag.aid).all()
    # 评论数量
    marks = Mark.query.all()
    # marks_num1 = Mark.query.count()
    # print(marks_num1, type(marks_num1))
    marks_num = len(marks)
    # print(marks_num,type(marks_num))
    # 根据ｕｉｄ找用户名
    # articles = db.session.query(Article, Category).filter(Article.cid == Category.cid, Category.cid == cid).all()
    usrname = db.session.query(User.username).filter(Mark.uid == User.uid).all()
    # print(usrname,type(usrname))
    # 根据用户名查找ｕｉｄ
    # 最近3篇文章
    three_articles = Article.query.order_by(-Article.create_time).all()[:3]
    three = len(three_articles)
    return render_template("post.html",**locals())

@bp.route('/verify/')
def verify_code():
    result = vc.generate()
    # 把验证码字符串保存到session
    session['code']= vc.code
    response = make_response(result)
    response.headers["Content-Type"] = "image/png"
    #返回图片
    return response

#短信验证
@bp.route('/send/',methods=['GET','POST'])
def send_sms():
    phone = request.values.get('phone')
    # print(phone)
    if phone:
        # 产生验证码
        num = randint(1000, 9999)
        # 添加到session
        session['phonecode'] = str(num)
        para = "{'number':'%d'}" % num
        res = sms.send(phone, para)
        print(res, type(res))
        return jsonify({'code': 1, 'msg': '发送成功'})
    return jsonify({"code": 0, 'msg': "电话号码不存在"})

@bp.route("/register/",methods=['GET','POST'])
def register_user():
    form = RegisterCheck(request.form)
    # print(form)
    if request.method == 'POST':
        # print("123")
        # 验证成功，返回True，否则返回False
        if form:
            # 获取验证数据
            username = form.username.data
            phone = form.phone.data
            password = form.password.data
            user = User(username=username)
            # 保存用户信息
            user.phone = phone
            user.password = generate_password_hash('password')
            # user.password = hashlib.sha1(password.encode('utf8')).hexdigest()
            db.session.add(user)
            db.session.commit()
            return redirect("/")
    return render_template("register.htm",**locals())

@bp.route("/addmark/",methods=['GET','POST'])
def add_mark():
    form = MarkCheck(request.form)
    if request.method == 'POST':
        if form:
            # 获取验证数据
            username = form.username.data
            uid = db.session.query(User.uid).filter(User.username == username).first() # 查询有问题
            print(uid, type(uid))
            content = form.content.data
            mark = Mark(uid=uid)
            # 保存用户信息
            mark.uid = uid[0]
            mark.content = content
            db.session.add(mark)
            db.session.commit()
            return redirect("/")
    return render_template("login.htm")


@us.route("/login/",methods=["GET","POST"])
def user_login():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')
        print(username,password)
        user = User.query.filter(User.username == username, User.password == password).first()
        print(user)
        if user:
        # if check_password_hash(sqlpwd1, '123456'):
            # 使用登录管理记录用
            # 参数必须是User的对象
            login_user(user)
            return redirect(url_for("bp.index"))
        else:
            flash("用户名或密码错误")
    return render_template("login.htm")

@us.route("/reply/")
@login_required
def reply_article():
    return "回复"

# 退出登录
@us.route("/logout/")
def user_logout():
    # 退出登录
    logout_user()
    return redirect('/')

@us.route("/register/",methods=["GET","POST"])
def user_register():
    return render_template("register1.htm")

blog/templates/blog.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
{#            {% for i in range(0,article_num) %}#}
                {%  for article in pagination.items %}
              <!-- post -->
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{{ url_for('bp.list_post',aid = article[0].aid - 1 )}}"><img src="/static/img/blog-post-1.jpeg" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                      {% block scripts %}
                    {{ moment.include_jquery() }}
                    {{ moment.include_moment() }}
                        {% endblock %}
                    <div class="date meta-last">{{ moment(article[0].create_time).fromNow() }}</div>
                    <div class="category"><a href="#">{{categories[cid-1].name}}</a></div>
                  </div><a href="#">
                    <h3 class="h4">{{ article[0].title }}</h3></a>
                  <p class="text-muted">{{ article[0].content }}</p>
                    <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar"><img src="/static/img/avatar-3.jpg" alt="..." class="img-fluid"></div>
                      <div class="title"><span>John Doe</span></div></a>
                    <div class="date"><i class="icon-clock"></i> {{article[0].create_time}}</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{article[0].replies}}</div>
                  </footer>
                </div>
              </div>
                {% endfor %}
{#            {% endfor %}#}
{#             <div class="post col-xl-6">#}
{#                                <div class="post-thumbnail"><a href="{{ url_for('bp.list_post' )}}"><img src="/static/img/blog-post-2.jpg" alt="..." class="img-fluid"></a></div>#}
{#                                <div class="post-details">#}
{#                                  <div class="post-meta d-flex justify-content-between">#}
{#                                    <div class="date meta-last">时间差３</div>#}
{#                                    <div class="category"><a href="#">{{categories[cid-1].name}}</a></div>#}
{#                                  </div><a href="{{ url_for('bp.list_post')}}">#}
{#                                    <h3 class="h4">无</h3></a>#}
{#                                  <p class="text-muted">文章不存在</p>#}
{#                                  <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">#}
{#                                      <div class="avatar"><img src="/static/img/avatar-2.jpg" alt="..." class="img-fluid"></div>#}
{#                                      <div class="title"><span>John Doe</span></div></a>#}
{#                                    <div class="date"><i class="icon-clock"></i> </div>#}
{#                                   <div class="comments meta-last"><i class="icon-comment"></i>0</div>#}
{#                                  </div>#}
{#                                </div>#}
{#                              </div>#}




{#                {% if article_num %2 != 0 %}#}
{#                              <!-- post -->#}
{#                             <div class="post col-xl-6">#}
{#                                <div class="post-thumbnail"><a href="{{ url_for('bp.list_post',aid = articles[i][0].aid - 1 )}}"><img src="/static/img/blog-post-2.jpg" alt="..." class="img-fluid"></a></div>#}
{#                                <div class="post-details">#}
{#                                  <div class="post-meta d-flex justify-content-between">#}
{#                                    <div class="date meta-last">时间差２</div>#}
{#                                    <div class="category"><a href="#">{{categories[cid-1].name}}</a></div>#}
{#                                  </div><a href="{{ url_for('bp.list_post',aid = articles[i][0].aid - 1 )}}">#}
{#                                    <h3 class="h4">{{ articles[i][0].title }}</h3></a>#}
{#                                  <p class="text-muted">{{ articles[i][0].content }}</p>#}
{#                                 <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">#}
{#                                      <div class="avatar"><img src="/static/img/avatar-2.jpg" alt="..." class="img-fluid"></div>#}
{#                                      <div class="title"><span>John Doe</span></div></a>#}
{#                                    <div class="date"><i class="icon-clock"></i> {{ articles[i][0].create_time }}</div>#}
{#                                    <div class="comments meta-last"><i class="icon-comment"></i>{{ articles[i][0].reples }}</div>#}
{#                                  </div>#}
{#                                </div>#}
{#                              </div>#}
{#                              {% else %}#}
{#                                  <div class="post col-xl-6">#}
{#                                <div class="post-thumbnail"><a href="{{ url_for('bp.list_post',aid = articles[i][0].aid - 1 )}}"><img src="/static/img/blog-post-2.jpg" alt="..." class="img-fluid"></a></div>#}
{#                                <div class="post-details">#}
{#                                  <div class="post-meta d-flex justify-content-between">#}
{#                                    <div class="date meta-last">时间差３</div>#}
{#                                    <div class="category"><a href="#">{{categories[cid-1].name}}</a></div>#}
{#                                  </div><a href="{{ url_for('bp.list_post',aid = articles[i][0].aid - 1)}}">#}
{#                                    <h3 class="h4">无</h3></a>#}
{#                                  <p class="text-muted">文章不存在</p>#}
{#                                  <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">#}
{#                                      <div class="avatar"><img src="/static/img/avatar-2.jpg" alt="..." class="img-fluid"></div>#}
{#                                      <div class="title"><span>John Doe</span></div></a>#}
{#                                    <div class="date"><i class="icon-clock"></i> </div>#}
{#                                   <div class="comments meta-last"><i class="icon-comment"></i>0</div>#}
{#                                  </div>#}
{#                                </div>#}
{#                              </div>#}
{#                                {% endif %}#}
{#             {% endfor %}#}

            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                <li class="page-item"><a href="{{ url_for('bp.list_article',cid=cid,page=cidnum[0][0])}}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
{#               {% for j in cidnum %}#}
                  {% for i in range(1,3) %}
                <li class="page-item"><a href="{{ url_for('bp.list_article',cid=cid,page=i )}}" class="page-link active">{{ i }}</a></li>
                    {% endfor %}
{#              {% endfor %}#}
                <li class="page-item"><a href="{{ url_for('bp.list_article',cid=cid,page=2)}}" class="page-link"><i class="fa fa-angle-right"></i></a></li>
              </ul>
            </nav>
          </div>
        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="#" class="search-form">
              <div class="form-group">
                <input type="search" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
          {% for i  in range(0, three) %}
            <div class="blog-posts"><a href="{{ url_for('bp.list_post',aid=three_articles[i].aid - 1)}}">
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ url_for('static',filename=three_articles[i].picture) }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ three_articles[i].title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i> {{ three_articles[i].hits }}</div>
                      <div class="comments"><i class="icon-comment"></i>{{ three_articles[i].replies }}</div>
                    </div>
                  </div>
                </div></a>
                    <a href="{{ url_for('bp.list_post',aid=three_articles[i].aid - 1) }}">
                  {% endfor %}
            </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">分类</h3>
            </header>
              {% for category in categories %}
             <div class="item d-flex justify-content-between"><a href="{{ url_for('bp.list_article',cid=category.cid) }}">{{category.name}}</a><span>{{ category.num }}</span></div>
             {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
          <div class="widget tags">       
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <ul class="list-inline">
                {% for i in range(0,tags_num) %}
              <li class="list-inline-item"><a href="#" class="tag">#{{ tags[i].name }}</a></li>
                {% endfor %}
            </ul>
          </div>
        </aside>
      </div>
    </div>
{% endblock %}

blog/templates/list.html
{% extends "bootstrap/base.html" %}

{% block content %}
<div class="bs-example" data-example-id="simple-table">
    <table class="table">
      <caption>Optional table caption.</caption>
      <thead>
        <tr>

          <th>Last Name</th>
          <th>Username</th>
        </tr>
      </thead>
      <tbody>
      {% for article in pagination.items %}
        <tr>

          <td>{{ article.title }}</td>
          <td>{{ article.content }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
    {% from "page.html" import show_pagination %}
{{ show_pagination(pagination,'bp.list_article') }}
{% endblock %}

blog/templates/page.html
{% macro show_pagination(pagination, endpoint) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {# 上一页 #}
            <li {% if not pagination.has_prev %}class="disabled"{% endif %}>
                <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            {# 中间页码 #}
            {% for p in pagination.iter_pages() %}
                {% if p %}
                    <li {% if pagination.page == p %}class="active"{% endif %}><a href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a></li>
                {% else %}
                    <li><a href="#">&hellip;</a></li>
                {% endif %}
            {% endfor %}

            {# 下一页 #}
            <li {% if not pagination.has_next %}class="disabled"{% endif %}>
                <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}

blog/templates/post.html
{% extends "common/base.html" %}
{% block content %}
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="index.html" class="navbar-brand">Bootstrap Blog</a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="index.html" class="nav-link ">Home</a>
              </li>
              <li class="nav-item"><a href="blog.html" class="nav-link ">Blog</a>
              </li>
              <li class="nav-item"><a href="post.html" class="nav-link active ">Post</a>
              </li>
              <li class="nav-item"><a href="#" class="nav-link ">Contact</a>
              </li>
            </ul>
            <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div>
            <ul class="langs navbar-text"><a href="#" class="active">EN</a><span>           </span><a href="#">ES</a></ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8"> 
          <div class="container">
            <div class="post-single">
              <div class="post-thumbnail"><img src="/static/img/blog-post-3.jpeg" alt="..." class="img-fluid"></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="category"><a href="#">Business</a><a href="#">Financial</a></div>
                </div>
                <h1>{{ articles[aid].title }}<a href="#"><i class="fa fa-bookmark-o"></i></a></h1>
                <div class="post-footer d-flex align-items-center flex-column flex-sm-row"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="/static/img/avatar-1.jpg" alt="..." class="img-fluid"></div>
                    <div class="title"><span>John Doe</span></div></a>
                  <div class="d-flex align-items-center flex-wrap">
                    <div class="date"><i class="icon-clock"></i> {{ articles[aid].create_time }}</div>
                    <div class="views"><i class="icon-eye"></i> {{ articles[aid].hits }}</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{ articles[aid].replies }}</div>
                  </div>
                </div>
                <div class="post-body">
                  <p class="lead">{{ articles[aid].content }}</p>
                  <p>{{ articles[aid].content }}</p>
                    {#                   <p> <img src="/static/img/featured-pic-3.jpeg" alt="..." class="img-fluid"></p>
                    {#                  <h3>Lorem Ipsum Dolor</h3>
                    {#                  <p>div Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda temporibus iusto voluptates deleniti similique rerum ducimus sint ex odio saepe. Sapiente quae pariatur ratione quis perspiciatis deleniti accusantium</p>
                    {#                  <blockquote class="blockquote">
                    {#                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inaididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
                    {#                    <footer class="blockquote-footer">Someone famous in
                    {#                      <cite title="Source Title">Source Title</cite>
                    {#                    </footer>
                    {#                  </blockquote>
                    {#                  <p>quasi nam. Libero dicta eum recusandae, commodi, ad, autem at ea iusto numquam veritatis, officiis. Accusantium optio minus, voluptatem? Quia reprehenderit, veniam quibusdam provident, fugit iusto ullam voluptas neque soluta adipisci ad.</p>
                    {#                </div> #}
<div class="post-tags"><a href="#" class="tag"></a></div>
                <div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row"><a href="{{ url_for('bp.list_post',aid=aid - 1 )}}" class="prev-post text-left d-flex align-items-center">
                    <div class="icon prev"><i class="fa fa-angle-left"></i></div>
                    <div class="text"><strong class="text-primary">上一篇 </strong>
                      <h6>{{ articles[aid - 1].title }}</h6>
                    </div></a><a href="{{ url_for('bp.list_post',aid=aid + 1 )}}" class="next-post text-right d-flex align-items-center justify-content-end">
                    <div class="text"><strong class="text-primary">下一篇 </strong>
                      <h6>{{ articles[aid + 1].title }}</h6>
                    </div>
                    <div class="icon next"><i class="fa fa-angle-right">   </i></div></a></div>
                <div class="post-comments">
                  <header>
                    <h3 class="h6">Post Comments<span class="no-of-comments">{{ marks_num }}</span></h3>
                  </header>
                    {% for i in range(0,4) %}
                  <div class="comment">
                    <div class="comment-header d-flex justify-content-between">
                      <div class="user d-flex align-items-center">
                        <div class="image"><img src="/static/img/user.svg" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="title"><strong> {{ usrname[i][0] }} </strong><span class="date">{{ marks[i].create_time }}</span></div>
                      </div>
                    </div>
                    <div class="comment-body">
                      <p>{{ marks[i].content }} </p>
                    </div>
                  </div>
                    {% endfor %}
                <div class="add-comment">
                  <header>
                    <h3 class="h6">Leave a reply</h3>
                  </header>
                  <form  method="post" action={{ url_for('bp.add_mark') }} >
{#                        {{  form.csrf_token  }}#}
                    <div class="row">
                      <div class="form-group col-md-6">
                        <input type="text" name="username" id="username" placeholder="请输入您的姓名" class="form-control">
{#                          {% for error in form.username.errors %}#}
{#                                     <span style="color: orangered; font-size: 15px;float: right" >{{ error }}</span>#}
{#                                    {% endfor %}#}
                      </div>
                      <div class="form-group col-md-6">
                        <input type="email" name="username" id="email" placeholder="请输入您的邮箱" class="form-control">
{#                          {% for error in form.email.errors %}#}
{#                                     <span style="color: orangered; font-size: 15px;float: right" >{{ error }}</span>#}
{#                                    {% endfor %}#}
                      </div>
                      <div class="form-group col-md-12">
                        <textarea name="content" id="usercomment" placeholder="写个评论吧" class="form-control"></textarea>
{#                          {% for error in form.content.errors %}#}
{#                                     <span style="color: orangered; font-size: 15px;float: right" >{{ error }}</span>#}
{#                                    {% endfor %}#}
                      </div>
                      <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-secondary">Submit Comment</button>

                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="#" class="search-form">
              <div class="form-group">
                <input type="search" placeholder="What are you looking for?">
                <button type="submit" class="submit" value="提交"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
          {% for i  in range(0, three) %}
            <div class="blog-posts"><a href="{{ url_for('bp.list_post',aid=three_articles[i].aid - 1)}}">
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ url_for('static',filename=three_articles[i].picture) }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ three_articles[i].title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i> {{ three_articles[i].hits }}</div>
                      <div class="comments"><i class="icon-comment"></i>{{ three_articles[i].replies }}</div>
                    </div>
                  </div>
                </div></a>
                    <a href="{{ url_for('bp.list_post',aid=three_articles[i].aid - 1) }}">
                  {% endfor %}
            </div>
          <!-- Widget [Categories Widget]-->
        <div class="widget categories">
            <header>
              <h3 class="h6">分类</h3>
            </header>
              {% for category in categories %}
             <div class="item d-flex justify-content-between"><a href="{{ url_for('bp.list_article',cid=category.cid) }}">{{category.name}}</a><span>{{ category.num }}</span></div>
             {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
          <div class="widget tags">
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <ul class="list-inline">
                {% for i in range(0,tags_num) %}
              <li class="list-inline-item"><a href="#" class="tag">#{{ tags[i].name }}</a></li>
                {% endfor %}
            </ul>
          </div>
        </aside>
      </div>
    </div>
{% endblock content %}