Tblog/App/urls.py
from django.urls import path
from App import views
app_name = 'App'

urlpatterns = [
    path('', views.index, name='index'),
    # 左边导航栏
    path('left/',views.public_left, name='left'),

    # 右边的标题栏
    path('header/', views.public_header, name='header'),

    # 主窗口，内容展示
    path('main/',views.public_main, name='main'),
    path('main/<int:cid>/',views.public_main, name='main'),
    path('main/<int:cid>/<int:page>/',views.public_main, name='main2'),
    # 修改密码
    path("change_psw/", views.change_psw, name="change_psw.html"),
    # 修改用户信息
    path("change_user/<int:uid>", views.change_user, name="change_user.html"),
    # 登录
    path("loginb/", views.loginb, name='loginb.html'),
    # 退出
    path("login_out/", views.user_loginout, name='loginb.html'),

    # 用户管理页面
    path("tupian_pc_index/", views.tupian_pc_index, name="tupian_pc_index"),
    path("tupian_pc_index/<int:uid>/", views.tupian_pc_index, name="tupian_pc_index"),
    path("tupian_pc_index/<int:uid>/<int:page>", views.tupian_pc_index, name="tupian_pc_index"),

    # 评论设置页面
    path("xitong_set/", views.xitong_set, name='xitong_set'),
    path("xitong_set/<int:uid>/", views.xitong_set, name='xitong_set'),
    path("xitong_set/<int:uid>/<int:page>/", views.xitong_set, name='xitong_set'),

    path("public_super_cg/", views.public_super_cg, name='public_super_cg'),
    # 文章发布
    path("wenzhang_xinwen_fabu/", views.wenzhang_xinwen_fabu, name='wenzhang_xinwen_fabu'),
    # 添加评论
    path("add_mark/", views.add_mark, name='add_mark'),
    # 文章修改
    path("wenzhang_xinwen_xiugai/<int:aid>/<int:cid>/", views.wenzhang_xinwen_xiugai, name='wenzhang_xinwen_xiugai'),
    # 评论修改
    path("mark_xiugai/<int:mid>/<int:uid>/", views.mark_xiugai, name='mark_xiugai'),
    # 验证码
    path("get_verify_img",views.get_verify_img,name='get_verify_img'),

    #　注册用户
    path("user_register",views.user_register,name='user_register'),

    # 文件上传
    path("upload/",views.upload,name='upload'),

    # 文件删除
    path("delete/<int:aid>/<int:cid>/<int:page>/",views.del_article,name='del_article'),
    # 用户删除
    path("delete/<int:uid>/",views.del_user,name='del_user'),
    # 评论删除
    path("del_mark/<int:mid>/<int:uid>/<int:page>/", views.del_mark, name='del_mark'),

]

Tblog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("App.urls")),
    path('tinymce/', include('tinymce.urls')),
]

Tblog/templates/change_psw.html
{% load staticfiles %}
<!DOCTYPE html>
<html class=" js csstransforms3d">
<head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>博客后台管理系统</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/page.css' %}">
	<!--[if lte IE 8]>
	<link href="{% static 'css/ie8.css' %}" rel="stylesheet" type="text/css"/>
	<![endif]-->
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
	<!--[if IE]>
	<script src="http://libs.useso.com/js/html5shiv/3.7/html5shiv.min.js"></script>
	<![endif]-->
</head>

<body style="background: #f6f5fa;">
	<!--content S-->
	<div class="super-content">
		<div class="superCtab">
			<div class="publishArt">
                <table>
            <tr>
                <td>当前登录用户：</td>
                <td>{{ username }}</td>
                <td><a href="/loginb/">退出</a></td>
                <td><a href="{% url 'App:main' %}">用户中心</a></td>
            </tr>
        </table>
				<h4>修改密码</h4>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="pubMain">
					<h5 class="pubtitle">旧密码</h5>
					<div class="pub-txt-bar">
						<input type="password" name="oldpwd" class="shuruTxt shuruTxt2"><b class="error"></b>

						<div class="errorBox">{{msg}}</div>

					</div>
					<h5 class="pubtitle">新密码<span>（数字、字母、符号组合，最少8个字符）</span></h5>
					<div class="pub-txt-bar">
						<input type="password" name="newpwd" class="shuruTxt shuruTxt2"><b class="error"></b>
						<div class="errorBox">{{form.newpwd.errors}}</div>
					</div>
					<h5 class="pubtitle">确认密码</h5>
					<div class="pub-txt-bar">
						<input type="password"  name="cfmpwd" class="shuruTxt shuruTxt2"><b class="error"></b>
						<div class="errorBox">{{form.cfmpwd.errors}}</div>
					</div>
					<div class="pub-btn">
						<input type="submit" id="" value="确定" class="saveBtn">
						<input type="button" id="" value="重置" class="resetBtn">
					</div>
				</div>
                </form>

			</div>
		
		</div>
		<!--main-->
		
	</div>
	<!--content E-->
	


</body></html>

Tblog/templates/change_user.html
{% load staticfiles %}
<!DOCTYPE html>
<html class=" js csstransforms3d">
<head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>博客后台管理系统</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/page.css' %}">
	<!--[if lte IE 8]>
	<link href="{% static 'css/ie8.css' %}" rel="stylesheet" type="text/css"/>
	<![endif]-->
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
	<!--[if IE]>
	<script src="http://libs.useso.com/js/html5shiv/3.7/html5shiv.min.js"></script>
	<![endif]-->
</head>

<body style="background: #f6f5fa;">
	<!--content S-->
	<div class="super-content">
		<div class="superCtab">
			<div class="publishArt">
                <table>
            <tr>
                <td>当前登录用户：</td>
                <td>{{ username }}</td>
                <td><a href="/loginb/">退出</a></td>
                <td><a href="{% url 'App:main' %}">用户中心</a></td>
            </tr>
        </table>
				<h4>修改密码</h4>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="pubMain">
                        <h5 class="pubtitle">用户名</h5>
					<div class="pub-txt-bar">
						<input type="text" name="username" value="{{ user.username }}" class="shuruTxt shuruTxt2"><b></b>

					<h5 class="pubtitle">旧密码</h5>
					<div class="pub-txt-bar">
						<input type="password" name="oldpwd" class="shuruTxt shuruTxt2"><b class="error"></b>
						<div class="errorBox">{{msg}}</div>

					</div>
					<h5 class="pubtitle">新密码<span>（数字、字母、符号组合，最少8个字符）</span></h5>
					<div class="pub-txt-bar">
						<input type="password" name="newpwd" class="shuruTxt shuruTxt2"><b class="error"></b>
						<div class="errorBox">{{form.newpwd.errors}}</div>
					</div>
					<h5 class="pubtitle">确认密码</h5>
					<div class="pub-txt-bar">
						<input type="password"  name="cfmpwd" class="shuruTxt shuruTxt2"><b class="error"></b>
						<div class="errorBox">{{form.cfmpwd.errors}}</div>
					</div>
					<div class="pub-btn">
						<input type="submit" id="" value="确定" class="saveBtn">
						<input type="button" id="" value="重置" class="resetBtn">
					</div>
				</div>
                </form>

			</div>
		
		</div>
		<!--main-->
		
	</div>
	<!--content E-->
	


</body></html>

Tblog/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="/static/tiny_mce/tiny_mce.js"></script>
    <script>
     tinyMCE.init({
       'mode':'textareas',
       'theme':'advanced',
        'width':450,
       'height':300
    })</script>
</head>
<body>
<form action="{% url 'App:wenzhang_xinwen_fabu' %}" method="post">
    <textarea name="comment_content">富文本</textarea>
    <input type="submit" value="提交评论" class="btn btn-default">
</form>
</body>
</html>

Tblog/templates/image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'App:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="photo"> <br>
    <input type="submit" value="确定上传">
</form>
</body>
</html>

Tblog/templates/public_left.html
<!DOCTYPE html>
<html class=" js csstransforms3d"><head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>公共侧边栏</title>
	<link rel="stylesheet" href="/static/css/base.css">
	<link rel="stylesheet" href="/static/css/page.css">
	<!--[if lte IE 8]>
	<link href="css/ie8.css" rel="stylesheet" type="text/css"/>
	<![endif]-->
	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/main.js"></script>
	<script type="text/javascript" src="/static/js/modernizr.js"></script>
	<!--[if IE]>
	<script src="http://libs.useso.com/js/html5shiv/3.7/html5shiv.min.js"></script>
	<![endif]-->
</head>

<body>
	<!--side S-->
	<div class="super-side-menu">
		<div class="logo"><a href="public_super_cg.html" target="_parent"><img src="/static/images/logo.png"></a></div>
		
		<div class="side-menu">
			<ul>
				<li class=""><a href="{% url 'App:main' %}" target="Mainindex"><i class="ico-1"></i>文章管理</a></li>
{#				<li><a href="huodong_guanli.html" target="Mainindex"><i class="ico-2"></i>活动管理</a></li>#}
{#				<li class="on"><a href="xiangce_Guanli.html" target="Mainindex"><i class="ico-3"></i>相册管理</a></li>#}
				<li><a href="{% url 'App:tupian_pc_index' %}" target="Mainindex"><i class="ico-4"></i>用户管理</a></li>
{#				<li><a href="zixun_Team.html" target="Mainindex"><i class="ico-5"></i>咨询管理</a></li>#}
{#				<li><a href="muban_Guanli.html" target="Mainindex"><i class="ico-6"></i>模板管理</a></li>#}
				<li><a href="{% url 'App:xitong_set' %}" target="Mainindex"><i class="ico-7"></i>评论管理</a></li>
			</ul>
		</div>
	</div>
	<!--side E-->

<script type="text/javascript">
	$(function(){
		$('.side-menu li').click(function(){
			$(this).addClass('on').siblings().removeClass('on');
		})
	})
</script>

</body></html>

Tblog/templates/wenzhang_xinwen.html
<!DOCTYPE html>
<html class=" js csstransforms3d"><head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>文章发布</title>
	<link rel="stylesheet" href="/static/css/base.css">
	<link rel="stylesheet" href="/static/css/page.css">

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/main.js"></script>
	<script type="text/javascript" src="/static/js/modernizr.js"></script>

</head>

<body style="background: #f6f5fa;">

	<!--content S-->
	<div class="super-content RightMain" id="RightMain">
		
		<!--header-->
		<div class="superCtab">
			<div class="ctab-title clearfix"><h3>文章发布</h3><a href="javascript:;" class="sp-column"><i class="ico-mng"></i>栏目管理</a></div>
			
			<div class="ctab-Main">
				<div class="ctab-Main-title">
					<ul class="clearfix">
{#						<li class="cur"><a href="wenzhang_xinwen.html">新闻动态</a></li>#}
						{% for cateory in categories %}
                           <li><a href="{% url 'App:main' cid=cateory.cid  %}">{{ cateory.name }}</a></li>
                        {% endfor %}
                      <script>
                          $(".ctab-Main-title li").eq({{ pos }}).addClass('cur')

                      </script>
					</ul>
				</div>
				
				<div class="ctab-Mian-cont">
					<div class="Mian-cont-btn clearfix">
						<div class="operateBtn">
							<a href="{% url 'App:wenzhang_xinwen_fabu' %}" class="greenbtn publish">发布文章</a>
{#							<a href="javascript:;" class="greenbtn add sp-add">添加分类</a>#}
{#							<a href="javascript:;" class="greenbtn add sp-photo" id="preview">栏目图片</a>#}
{#							<a href="javascript:;" class="modify sp-modify" id="sp-modify">修改</a>#}
						</div>
						<div class="searchBar">
                            <form action="{% url 'App:main' cid=cid %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="cid" value="{{ cid }}">
                                <input type="text" name="keyword" value="" class="form-control srhTxt" placeholder="输入标题关键字搜索">
                                <input type="submit" class="srhBtn" value="">
                            </form>
						</div>
					</div>
{#					<div class="super-label clearfix">#}
{#						<a href="#">行业新闻<em style="display: none;"></em></a><a href="#">保险常识<em style="display: none;"></em></a>#}
{#					</div>#}
{#					#}
					<div class="Mian-cont-wrap">
						<div class="defaultTab-T">
							<table border="0" cellspacing="0" cellpadding="0" class="defaultTable">
								<tbody><tr><th class="t_1">文章ID</th><th class="t_2">文章标题</th><th class="t_3">发布时间</th><th class="t_4">操作</th></tr>
							</tbody></table>
						</div>
						<table border="0" cellspacing="0" cellpadding="0" class="defaultTable defaultTable2">
							<tbody>
							{% for article in pager.object_list %}
							<tr>
								<td class="t_1">{{ article.aid }}</td>
								<td class="t_2"><a href="#">{{ article.title }}</a></td>
								<td class="t_3">{{ article.create_time }}</td>
								<td class="t_4"><div class="btn"><a href="{% url 'App:wenzhang_xinwen_xiugai' aid=article.aid cid=cid  %}" class="
modify">修改</a><a href="{% url 'App:del_article' aid=article.aid cid=cid page=page %}" class="delete">删除</a></div></td>
							</tr>
                            {% endfor %}


						</tbody></table>
						<!--pages S-->
						<div class="pageSelect">
							<span>共 <b>{{ paginator.count }}</b> 条 每页 <b>{{ paginator.per_page }} </b>条   {{pager.number}}/{{ paginator.num_pages }}</span>
							<div class="pageWrap">
								<a class="pagePre" href="{% url 'App:main2' cid=cid page=page|add:-1 %}"><i class="ico-pre">&nbsp;</i></a>
								 {% for page in paginator.page_range %}
                                        <a href="{% url 'App:main2' cid=cid page=page %}" class="pagenumb">{{ page }}</a>
                                 {% endfor %}

								<a href="{% url 'App:main2' cid=cid page=page|add:1%}" class="pagenext"><i class="ico-next">&nbsp;</i></a>

							</div>
						</div>
						<!--pages E-->
					</div>
				
				</div>
			</div>
		</div>
		<!--main-->
		
	</div>
	<!--content E-->
	
	<div class="layuiBg"></div><!--公共遮罩-->
	<!--点击修改弹出层-->
	<div class="imgXgbox layuiBox">
		<div class="layer-title clearfix"><h2>修改栏目图片</h2><span class="layerClose"></span></div>
		<div class="layer-content">
			<div class="XgfileImg"><img src="/static/images/bg_img_sc.jpg"><input id="fileImage" class="fileImageSlect" type="file" size="30" name="fileselect[]"></div>
			<p class="onclktip">（点击图片可重新上传）</p>
			<div class="Xgimglink clearfix"><span>图片链接：</span><input type="text" value=""></div>
			<div class="XgBtn"><input type="button" value="保存" class="saveBtn"></div>
		</div>
	</div>

	<!--栏目管理-->
	<div class="Columnbox layuiBox">
		<div class="layer-title clearfix"><h2>栏目管理</h2><span class="layerClose"></span></div>
		<div class="layer-content">
			<ul class="colu-title clearfix">
				<li class="li-1">栏目名称</li><li class="li-2">英文名称</li><li class="li-3">操作</li><li class="li-4">同步开关</li>
			</ul>
			<div class="colu-list">
				<ul class="colu-cont clearfix active">
					<li class="li-1"><i class="ico"></i>新闻动态</li><li class="li-2">life</li><li class="li-3"><a href="javascript:;" class="colu-xg" data-id="xg1">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d1" class="chk_4"><label for="checkbox_d1"></label></li>
				</ul>
				<div class="colunext" style="display: block;">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg" data-id="xg2">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--新闻动态-->
			<div class="colu-list">
				<ul class="colu-cont clearfix">
					<li class="li-1"><i class="ico"></i>品尚生活</li><li class="li-2">news</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d2" class="chk_4"><label for="checkbox_d2"></label></li>
				</ul>
				<div class="colunext">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--品尚生活-->
			<div class="colu-list">
				<ul class="colu-cont clearfix">
					<li class="li-1"><i class="ico"></i>卓越联盟</li><li class="li-2">allance</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d3" class="chk_4"><label for="checkbox_d3"></label></li>
				</ul>
				<div class="colunext">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--卓越联盟-->
			<div class="colu-list">
				<ul class="colu-cont clearfix">
					<li class="li-1"><i class="ico"></i>招贤纳士</li><li class="li-2">managers</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d4" class="chk_4" checked=""><label for="checkbox_d4"></label></li>
				</ul>
				<div class="colunext">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--招贤纳士-->
			<div class="colu-list">
				<ul class="colu-cont clearfix">
					<li class="li-1"><i class="ico"></i>客户见证</li><li class="li-2">witness</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d5" class="chk_4" checked=""><label for="checkbox_d5"></label></li>
				</ul>
				<div class="colunext">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--客户见证-->
			<div class="colu-list">
				<ul class="colu-cont clearfix">
					<li class="li-1"><i class="ico"></i>热门产品</li><li class="li-2">product</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"><input type="checkbox" id="checkbox_d6" class="chk_4" checked=""><label for="checkbox_d6"></label></li>
				</ul>
				<div class="colunext">
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
					<ul class="colu-next clearfix">
						<li class="li-1"><i class="ico"></i>行业新闻</li><li class="li-2"></li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li>
					</ul>
				</div>
			</div><!--热门产品-->
			<div class="colu-list">
				<ul class="clearfix colu-cont-no">
					<li class="li-1"><i class="ico"></i>关于我们</li><li class="li-2">about</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"></li>
				</ul>
			</div><!--关于我们-->
			<div class="colu-list">
				<ul class="clearfix colu-cont-no">
					<li class="li-1"><i class="ico"></i>联系方式</li><li class="li-2">contact</li><li class="li-3"><a href="javascript:;" class="colu-xg">修改</a></li><li class="li-4"></li>
				</ul>
			</div><!--联系方式-->
			
		</div>
	</div>
	<!--栏目管理－修改-->
	<div class="ColumnXgbox layuiBox">
		<div class="layer-title clearfix"><h2>添加分类</h2><span class="layerClose"></span></div>
		<div class="layer-content">
			<div class="aFllink clearfix"><span>修改名称：</span><input type="text" value=""></div>
			<div class="aFllink clearfix"><span>英文名称：</span><input type="text" value=""></div>
			<div class="aFlBtn"><input type="button" value="保存" class="saveBtn"></div>
		</div>
	</div>



<script type="text/javascript" src="/static/js/zxxFile.js"></script>
<script>
var params = {
	fileInput: $("#fileImage").get(0),
	upButton: $("#fileSubmit").get(0),
	url: $("#uploadForm").attr("action"),
	filter: function(files) {
		var arrFiles = [];
		for (var i = 0, file; file = files[i]; i++) {
			if (file.type.indexOf("image") == 0) {
				if (file.size >= 512000) {
					alert('您这张"'+ file.name +'"图片大小过大，应小于500k');	
				} else {
					arrFiles.push(file);	
				}			
			} else {
				alert('文件"' + file.name + '"不是图片。');	
			}
		}
		return arrFiles;
	},
	onSelect: function(files) {
		var html = '', i = 0;
		$("#preview").html('<div class="upload_loading"></div>');
		var funAppendImage = function() {
			file = files[i];
			if (file) {
				var reader = new FileReader()
				reader.onload = function(e) {
					$('.XgfileImg img').attr('src', e.target.result);
					$('.sp-photo').addClass('cur');
					html = html + '<div id="uploadList_'+ i +'" class="upload_append_list"><p><span>' + file.name + '</span>'+ 
						'<a href="javascript:" class="upload_delete" title="删除" data-index="'+ i +'">删除</a>' +
					'</div>';
					
					i++;
					funAppendImage();
				}
				reader.readAsDataURL(file);
			} else {
				$("#preview").html(html);
				if (html) {
					//删除方法
					$(".upload_delete").click(function() {
						ZXXFILE.funDeleteFile(files[parseInt($(this).attr("data-index"))]);
						$('.sp-photo').removeClass('cur').html('栏目图片');
						return false;	
					});
					//提交按钮显示
					$("#fileSubmit").show();	
				} else {
					//提交按钮隐藏
					$("#fileSubmit").hide();	
				}
			}
		};
		funAppendImage();		
	},
	onDelete: function(file) {
		$("#uploadList_" + file.index).fadeOut();
	},
	onDragOver: function() {
		$(this).addClass("upload_drag_hover");
	},
	onDragLeave: function() {
		$(this).removeClass("upload_drag_hover");
	},
	onProgress: function(file, loaded, total) {
		var eleProgress = $("#uploadProgress_" + file.index), percent = (loaded / total * 100).toFixed(2) + '%';
		eleProgress.show().html(percent);
	},
	onSuccess: function(file, response) {
		$("#uploadInf").append("<p>上传成功，图片地址是：" + response + "</p>");
	},
	onFailure: function(file) {
		$("#uploadInf").append("<p>图片" + file.name + "上传失败！</p>");	
		$("#uploadImage_" + file.index).css("opacity", 0.2);
	},
	onComplete: function() {
		//提交按钮隐藏
		$("#fileSubmit").hide();
		//file控件value置空
		$("#fileImage").val("");
		$("#uploadInf").append("<p>当前图片全部上传完毕，可继续添加上传。</p>");
	}
};
ZXXFILE = $.extend(ZXXFILE, params);
ZXXFILE.init();

</script>

</body></html>